name: build

on:
  push:
  pull_request:

jobs:
  desktop:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore .\Yokko.Desktop.slnf

      - name: Build
        run: dotnet build .\Yokko.Desktop.slnf --no-restore --configuration Release
